CLASS LHC_DATAMODEL DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR DataModel
        RESULT result,
      CheckSemanticKey FOR VALIDATE ON SAVE
            IMPORTING keys FOR DataModel~CheckSemanticKey.
ENDCLASS.

CLASS LHC_DATAMODEL IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD CheckSemanticKey.
  READ ENTITIES OF ZI_ACONN IN LOCAL MODE
  ENTITY DataModel FIELDS ( UUID CarrierID ConnectionID )
  WITH CORRESPONDING #( keys )
  RESULT DATA(connections).
  ENDMETHOD.

ENDCLASS.
